# https://travis-ci.org/tgbugs/hyputils
sudo: false
language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
branches:
  only:
    - master
  git:
    depth: 3

python:
  - 3.6
  - 3.7
  - 3.8

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - pip install --upgrade pytest pytest-cov
  - pip install pipenv
  - pip install coverage coveralls && export HAS_COVERALLS=1
  - pipenv install --dev --system --skip-lock --deploy

before_script:
  - createdb htest

script:
  - pipenv run pytest --cov=hyputils

after_success:
  - if [[ $HAS_COVERALLS && $TRAVIS_PYTHON_VERSION == 3.7 ]] ; then coveralls ; fi
