# https://travis-ci.org/tgbugs/hyputils
sudo: false
language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
branches:
  only:
    - master
  git:
    depth: 3

python:
  - 3.6

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10

services:
  - postgresql

install:
  - pip install pipenv
  - pip install coverage coveralls && export HAS_COVERALLS=1
  - pipenv install --system --skip-lock --deploy --verbose

before_script:
  - createdb htest

script:
  - PYTHONWARNINGS=default pipenv run pytest --cov=hyputils

after_success:
  - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi
